import Link from "next/link";
import { SectionHeading } from "@/components/SectionHeading";
import { certifications, education, experience, impactHighlights } from "@/data/resume";
import { profile } from "@/data/profile";

export default function ResumePage() {
  return <section className="container-shell py-20"><SectionHeading eyebrow="Resume" title="Power Platform development backed by enterprise delivery" body="An interactive version of the professional resume, connected to the technical evidence throughout this portfolio." />
    <div className="mt-8 flex flex-wrap gap-3">{profile.resumeUrl && <a href={profile.resumeUrl} className="primary-cta rounded-xl px-5 py-3 text-sm font-semibold">Open PDF resume ↗</a>}<Link href="/experience" className="secondary-cta rounded-xl px-5 py-3 text-sm font-semibold">Interactive experience</Link><a href={profile.githubUrl} target="_blank" rel="noreferrer" className="secondary-cta rounded-xl px-5 py-3 text-sm font-semibold">GitHub ↗</a></div>
    <div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{impactHighlights.map((item) => <article key={item.label} className="glass rounded-2xl p-5"><p className="text-3xl font-semibold text-white">{item.value}</p><p className="mt-2 text-sm leading-6 text-slate-400">{item.label}</p></article>)}</div>
    <div className="mt-14 space-y-5"><h2 className="text-2xl font-semibold text-white">Experience</h2>{experience.map((item) => <article key={`${item.company}-${item.period}`} className="glass rounded-3xl p-6 sm:p-8"><p className="text-xs uppercase tracking-[.16em] text-emerald-200">{item.period}</p><h3 className="mt-2 text-xl font-semibold text-white">{item.role}</h3><p className="mt-1 text-sm text-slate-400">{item.company} · {item.location}</p><div className="mt-4 flex flex-wrap gap-2">{item.technologies.map((t) => <span key={t} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-400">{t}</span>)}</div><ul className="mt-5 space-y-2 text-sm leading-6 text-slate-400">{item.bullets.map((b) => <li key={b} className="flex gap-3"><span className="text-sky-300">→</span><span>{b}</span></li>)}</ul></article>)}</div>
    <div className="mt-14 grid gap-5 lg:grid-cols-2"><div className="glass rounded-3xl p-7"><h2 className="text-2xl font-semibold text-white">Education</h2><div className="mt-5 space-y-4">{education.map((e) => <div key={e.degree}><p className="text-xs text-emerald-200">{e.period}</p><p className="mt-1 font-semibold text-white">{e.degree}</p><p className="text-sm text-slate-400">{e.school} · {e.detail}</p></div>)}</div></div><div className="glass rounded-3xl p-7"><h2 className="text-2xl font-semibold text-white">Certifications</h2><div className="mt-5 flex flex-wrap gap-2">{certifications.map((c) => <span key={c} className="rounded-xl border border-white/10 bg-white/[.025] px-3 py-2 text-sm text-slate-300">{c}</span>)}</div></div></div>
  </section>;
}
